apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.evento.dev
spec:
  group: evento.dev
  names:
    kind: Cluster
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                messaging:
                  type: object
                  properties:
                    managed:
                      type: object
                      properties:
                        kafka:
                          type: object
                          properties:
                            replicas:
                              type: integer
                              minimum: 1
                        zookeeper:
                          type: object
                          properties:
                            replicas:
                              type: integer
                              minimum: 1
                    external:
                      type: object
                      properties:
                        bootstrapServers:
                          type: string
                  oneOf:
                    - required: [managed]
                    - required: [external]
              required:
                - messaging
              description: >-
                The specification of the Kafka and ZooKeeper clusters.
                Managed cluster requires strimzi operator and uses a simplified version of
                https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.20.1/strimzi-cluster-operator-0.20.1.yaml
            status:
              type: object
              properties:
                message:
                  type: string