apiVersion: apps/v1
kind: Deployment
metadata:
  name: evento-operator
spec:
  selector:
    matchLabels:
      app: evento-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: evento-operator
    spec:
      serviceAccountName: evento-operator
      containers:
        - image: danielgazineu/evento-operator:0.1-SNAPSHOT
          name: evento-operator
          imagePullPolicy: Always