apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contexts.evento.dev
spec:
  scope: Namespaced
  group: evento.dev
  names:
    kind: Context
    listKind: ContextList
    plural: contexts
    singular: context
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                objectTypes:
                  type: array
                  items:
#                    each item in this array represents an object definition that may be reused by CRDs associated with
#                    this Context. i.e: A context may declare an object Balance, and both entities CheckingAccount and
#                    SavingsAccount may refer to that same object, by name.
                    type: object
                    properties:
                      name:
                        type: string
                      doc:
                        type: string
                      fields:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            doc:
                              type: string
                            primitiveType:
                              type: string
                              enum:
                                - type_null
                                - type_boolean
                                - type_int
                                - type_long
                                - type_float
                                - type_double
                                - type_bytes
                                - type_string
                            customType:
                              type: string
                          oneOf:
                            - required: [ name, primitiveType ]
                            - required: [ name, customType ]
                    required: [name, fields]