apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: evento-apicurio-
  ownerReferences:
    - apiVersion: apps/v1
      kind: Evento
      name: placeholder
      uid: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: evento-apicurio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: evento-apicurio
    spec:
      containers:
        - name: evento-apicurio
          image: docker.io/apicurio/apicurio-registry-mem:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP