kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: evento-operator
subjects:
  - kind: ServiceAccount
    name: evento-operator
    namespace: {NAMESPACE}
roleRef:
  kind: ClusterRole
  name: evento-operator
  apiGroup: rbac.authorization.k8s.io