apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evento-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - create
      - update
  - apiGroups:
      - registry.apicur.io
    resources:
      - apicurioregistries
    verbs:
      - list
      - get
      - create
      - update
      - delete
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
    verbs:
      - list
      - get
      - create
      - update
      - delete
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - list
      - get
      - create
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - evento.dev
    resources:
      - eventos
      - contexts
    verbs:
      - list
      - watch