#!/bin/bash

# dev/watch app: Watches the logs for a pod in the cluster. Runs kubectl -n "${NAMESPACE}" logs -f -l app="${APP}"

set -e
cd "$(dirname "$0")/.."
source dev/.functions.sh

# TODO change this to be the name of the container once it makes sense to watch anything else other than the operator
#if [ $# -lt 1 ]; then
#  echo "Expected one argument with the name of the component to watch"
#  exit 1
#fi

NAMESPACE=$(print_namespace "$@")
APP="evento-operator"

kubectl -n "${NAMESPACE}" logs -f -l app="${APP}"