apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entities.evento.dev
spec:
  scope: Namespaced
  group: evento.dev
  names:
    kind: Entity
    listKind: EntityList
    plural: entities
    singular: entity
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                doc:
                  type: string
                  description: Entity description.
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      fieldName:
                        type: string
                      fieldDoc:
                        type: string
                      fieldType:
                        type: object
                        properties:
                          fieldPrimitiveType:
                            type: string
                            enum:
                              - type_null
                              - type_boolean
                              - type_int
                              - type_long
                              - type_float
                              - type_double
                              - type_bytes
                              - type_string
                          fieldCustomType:
                            type: string
                          fieldMapValuesPrimitiveType:
                            type: string
                            enum:
                              - type_null
                              - type_boolean
                              - type_int
                              - type_long
                              - type_float
                              - type_double
                              - type_bytes
                              - type_string
                          fieldMapValuesCustomType:
                            type: string
                        oneOf:
                          - required: [ fieldPrimitiveType ]
                          - required: [ fieldCustomType ]
                          - required: [ fieldMapValuesPrimitiveType ]
                          - required: [ fieldMapValuesCustomType ]
              required: [fields]