apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-operator
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - list
      - get
      - create
      - update
  - apiGroups:
      - extensions
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - evento.dev
    resources:
      - examples
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list