kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-operator
subjects:
  - kind: ServiceAccount
    name: example-operator
    namespace: evento-master
roleRef:
  kind: ClusterRole
  name: example-operator
  apiGroup: rbac.authorization.k8s.io