#!/bin/bash

set -e
cd "$(dirname "$0")/.."
source dev/.functions.sh

EXAMPLES="control-plane/evento-operator/src/main/resources/examples"
NAMESPACE=$(print_namespace "$@")
CLUSTER=$(print_cluster "$@")

if [ -z "$CLUSTER" ]; then
  echo "--cluster option must be set"
  exit 1
fi

kubectl -n "$NAMESPACE" apply -f "${EXAMPLES}/clusters/${CLUSTER}.yaml"

CONTEXT=$(print_context "$@")

if [ -z "$CONTEXT" ]; then
  echo "--context wasn't provided, done."
  exit 0
fi

cat "${EXAMPLES}/contexts/${CONTEXT}.yaml" | sed "s/{CLUSTER}/$CLUSTER/g" | kubectl apply -n "$NAMESPACE" -f -
