apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator
spec:
  selector:
    matchLabels:
      app: example-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: example-operator
    spec:
      serviceAccountName: example-operator
      containers:
        - image: danielgazineu/example-operator:0.1-SNAPSHOT
          name: example-operator
          imagePullPolicy: Always